### ISSUE TITLE
Could we set LD_LIBRARY_PATH as default shell_env in container

### ISSUE THREAD

**Issue by pingsutw** [linkedin/TonY#404] opened 2019-12-03 11:39 UTC
If we want to read hdfs by `tf.io.gfile`, we need to specify **HADOOP_HDFS_HOME** and **LD_LIBRARY_PATH** as container shell environment variable. In some cases, user already set these variable in their machine,so could we directly set these variable as default. e.g. ` export HADOOP_HDFS_HOME=$HADOOP_HDFS_HOME` in worker

**Comment by oliverhu** [comment] 2019-12-03 18:50
Mm, we don't actually set those parameters for our jobs, it seems to automatically pick up local env. Are you using docker or virtual env zip?

**Comment by pingsutw** [comment] 2019-12-04 13:43
I follow this [link](https://github.com/linkedin/TonY/tree/master/tony-examples/mnist-tensorflow) to run MNIST example, and change working_dir to hdfs 
run with below command :
`java -cp $(hadoop classpath --glob):/root/git/TonY/tony-cli/build/libs/tony-cli-0.3.21-all.jar com.linkedin.tony.cli.ClusterSubmitter --python_venv=venv.zip --src_dir=/root/git/TonY/tony-examples/mnist-tensorflow/ --executes=mnist_distributed.py --task_params="--steps 1000 --data_dir /tmp/data --working_dir hdfs://master:8020/user/root/mnist" --conf_file=tensorflow.xml --python_binary_path=venv/bin/python3 --shell_env HADOOP_HDFS_HOME=$HADOOP_HDFS_HOME --shell_env LD_LIBRARY_PATH=$LD_LIBRARY_PATH`

if i don't specify **HADOOP_HDFS_HOME** and **LD_LIBRARY_PATH**, it will hangs with
```
2018-09-13 03:02:31.538790: E tensorflow/core/distributed_runtime/master.cc:272] CreateSession failed because worker /job:worker/replica:0/task:0 returned error: Unavailable: OS Error
INFO:tensorflow:An error was raised while a session was being created. This may be due to a preemption of a connected worker or parameter server. A new session will be created. Error: OS Error
INFO:tensorflow:Graph was finalized.
2018-09-13 03:03:33.792490: I tensorflow/core/distributed_runtime/master_session.cc:1150] Start master session ea811198d338cc1d with config: 
INFO:tensorflow:Waiting for model to be ready.  Ready_for_local_init_op:  Variables not initialized: conv1/Variable, conv1/Variable_1, conv2/Variable, conv2/Variable_1, fc1/Variable, fc1/Variable_1, fc2/Variable, fc2/Variable_1, global_step, adam_optimizer/beta1_power, adam_optimizer/beta2_power, conv1/Variable/Adam, conv1/Variable/Adam_1, conv1/Variable_1/Adam, conv1/Variable_1/Adam_1, conv2/Variable/Adam, conv2/Variable/Adam_1, conv2/Variable_1/Adam, conv2/Variable_1/Adam_1, fc1/Variable/Adam, fc1/Variable/Adam_1, fc1/Variable_1/Adam, fc1/Variable_1/Adam_1, fc2/Variable/Adam, fc2/Variable/Adam_1, fc2/Variable_1/Adam, fc2/Variable_1/Adam_1, ready: None
```

**Comment by oliverhu** [comment] 2019-12-04 17:34
I see, it is specified here https://github.com/linkedin/TonY#faq. not for every body tho.

**Comment by oliverhu** [comment] 2019-12-04 18:42
I guess i know your problem. the issue is $LD_LIBRARY_PATH is only set in your submission host (gateway or local host), but not set in the cluster machines.

**Comment by pingsutw** [comment] 2019-12-09 08:28
Thanks @oliverhu, I fixed it, I printed out the configuration in my containers, 
I found that there are some configuration missing in the cluster machines.

**Comment by oliverhu** [comment] 2019-12-09 20:09
cool! closing the ticket.

**Closed by oliverhu** 2019-12-09 20:09 UTC
